version: "3"
services:
  worker:
    hostname: worker
    image: enigmampc/worker_hw:testnet
    environment:
      - ENIGMA_ENV=TESTNET
      - SGX_MODE=HW
      - ETH_NODE_ADDRESS=http://parity:8545
      - KEY_MANAGEMENT_ADDRESS=http://km.testnet.services.enigma.co:3040
      # - MIN_CONFIRMATIONS=
      # - FORCE_NEW_ETH_ADDR=true
    ports:
      - "3346:3346"   # Json RPC
      - "10300:10300" # LibP2P
    volumes:
      - ./config/.enigma:/root/.enigma
  parity:
    image: parity/parity:v2.5.11-stable
    user: root
    volumes:
      - data-volume:/home/parity/.local/share/io.parity.ethereum/chains/kovan/db
    command: --chain kovan --jsonrpc-apis 'web3,eth,pubsub,net,parity,parity_pubsub,traces,rpc,secretstore,shh,shh_pubsub' --jsonrpc-interface 0.0.0.0 --jsonrpc-hosts="all"
    ports:
      - 8545:8545
      - 8546:8546
      - 8180:8180
      - 30303:30303
  monitor:
    image: buythewhale/ethstats_monitor
    volumes:
      - ./config/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro
  dashboard:
    image: buythewhale/ethstats
    volumes:
      - ./config/ws_secret.json:/eth-netstats/ws_secret.json:ro
    ports:
      - 3001:3000     
volumes:
  data-volume: