name: CI

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker images
      run: |
        make clone-all
        make build SGX_MODE=SW
    - name: Run the tests
      run: |
        cp .env.template .env
        docker-compose up --exit-code-from client & sleep 360 && docker-compose exec -T client make test
