name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker images
        run: |
          make clone-all BRANCH=develop
          make build SGX_MODE=SW DOCKER_TAG=develop
      - name: Run the tests
        run: |
          cp .env.template .env
          DOCKER_TAG=develop docker-compose up -d
          until ./is_ready.sh; do
            sleep 1
          done
          docker-compose exec -T client make test
